echo Updating...
wget https://github.com/sparksammy/callienaps-nw/blob/master/builds/callienaps_blue_main.dylib?raw=true -O callienaps.dylib
echo Launching...
DYLD_INSERT_LIBRARIES=callienaps.dylib /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
